name: retail_streaming
version: '1.0'
config-version: 2
profile: retail_profile
source-paths: ["models"]
model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  retail_streaming:
    +materialized: table
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +schema: gold
